'use client';
// This file is automatically generated. Do not modify.
import { User as FirebaseUser, onIdTokenChanged } from 'firebase/auth';
import { useEffect, useState } from 'react';
import { useAuth } from '../provider';
import {
  doc,
  DocumentReference,
  onSnapshot,
  FirestoreError,
} from 'firebase/firestore';
import { useFirestore } from '..';

export interface User extends FirebaseUser {
  role?: 'admin' | 'customer';
}

export function useUser() {
  const auth = useAuth();
  const firestore = useFirestore();
  const [user, setUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    const unsubscribe = onIdTokenChanged(auth, async (firebaseUser) => {
      if (firebaseUser) {
        try {
          const token = await firebaseUser.getIdTokenResult();
          const userDocRef = doc(
            firestore,
            'users',
            firebaseUser.uid
          ) as DocumentReference;

          const unsub = onSnapshot(
            userDocRef,
            (doc) => {
              if (doc.exists()) {
                const data = doc.data();
                setUser({
                  ...firebaseUser,
                  ...data,
                  role:
                    (data.role as 'admin' | 'customer') || token.claims.role,
                });
              } else {
                setUser({
                  ...firebaseUser,
                  role: token.claims.role as 'admin' | 'customer' | undefined,
                });
              }
              setIsLoading(false);
            },
            (err: FirestoreError) => {
              console.error('Error fetching user data:', err);
              setError(err);
              setIsLoading(false);
            }
          );
          return () => unsub();
        } catch (e) {
          console.error('Error getting id token', e);
          setError(e as Error);
          setUser(firebaseUser);
          setIsLoading(false);
        }
      } else {
        setUser(null);
        setIsLoading(false);
      }
    });

    return () => unsubscribe();
  }, [auth, firestore]);

  return { user, isLoading, error };
}
