'use client';
// This file is automatically generated. Do not modify.
import React from 'react';
import { FirebaseProvider } from './provider';
import { initializeFirebase } from '.';

export default function FirebaseClientProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const firebase = initializeFirebase();

  return <FirebaseProvider value={firebase}>{children}</FirebaseProvider>;
}
