// This file is automatically generated. Do not modify.

export type SecurityRuleContext = {
  path: string;
  operation: 'get' | 'list' | 'create' | 'update' | 'delete' | 'write';
  requestResourceData?: any;
};

/**
 * A custom error class that encapsulates information about a Firestore
 * permission error.
 *
 * This error is thrown by the client when a Firestore operation is denied by
 * security rules. It is then caught by the global error handler and displayed

 */
export class FirestorePermissionError extends Error {
  constructor(public context: SecurityRuleContext) {
    const { path, operation } = context;

    super(
      `Firestore operation '${operation}' on path '${path}' was denied by security rules.`
    );
    this.name = 'FirestorePermissionError';
  }
}
