'use client';
// This file is automatically generated. Do not modify.
import { getAnalytics, isSupported } from 'firebase/analytics';
import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { getAuth, Auth } from 'firebase/auth';
import { getFirestore, Firestore } from 'firebase/firestore';

import { firebaseConfig } from './config';

/**
 * The initialized Firebase app.
 *
 * This is a singleton that is initialized once and then reused.
 * We are using a function to initialize the app so that it is only initialized
 * when it is needed.
 *
 * @returns an object with the initialized Firebase app, Auth, and Firestore
 * instances.
 */
export function initializeFirebase(): {
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
} {
  const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
  const auth = getAuth(app);
  const firestore = getFirestore(app);
  if (typeof window !== 'undefined') {
    isSupported().then((supported) => {
      if (supported) {
        getAnalytics(app);
      }
    });
  }

  return { app, auth, firestore };
}

// These exports are for convenience and to avoid importing from the firebase
// package in every file.
export {
  useFirebase,
  useFirebaseApp,
  useFirestore,
  useAuth,
  FirebaseProvider,
} from './provider';
export { useUser } from './auth/use-user';
export type { User } from './auth/use-user';
