'use client';
// This file is automatically generated. Do not modify.
import React, { useEffect, useState } from 'react';
import { errorEmitter } from '../firebase/error-emitter';
import { FirestorePermissionError } from '../firebase/errors';
import { useToast } from '@/hooks/use-toast';

/**
 * A client component that listens for Firestore permission errors and
 * displays them as a toast notification.
 *
 * This component is intended to be used in the root layout of the application
 * to provide a consistent error handling experience for Firestore permission
 * errors.
 *
 */
const FirebaseErrorListener: React.FC = () => {
  const { toast } = useToast();

  useEffect(() => {
    const handleError = (error: FirestorePermissionError) => {
      console.error('Firestore Permission Error:', error.message, error.context);
      toast({
        variant: 'destructive',
        title: 'Permission Denied',
        description:
          "You don't have permission to perform this action. Check Firestore rules.",
      });
    };

    errorEmitter.on('permission-error', handleError);

    return () => {
      errorEmitter.off('permission-error', handleError);
    };
  }, [toast]);

  return null;
};

export default FirebaseErrorListener;
